Num1=int(input("enter the first number:"))
Num2=int(input("enter the second number:"))
print("summation :",(Num1+Num2))
print("difference :",(Num1-Num2))
print("product :",(Num1*Num2))
print("quotient :",(Num1/Num2))
print("remainder :",(Num1%Num2))
print("exponent :",(Num1**Num2))
print("positive floor division :",(Num1//Num2))
print("negative floor division :",(-Num1//Num2))